name: build and test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '8.0.100' # The .NET SDK version to use

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v3
      with:
        ref: dev   # Always build from dev branch

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Debug - List files
      run: ls -R

    - name: Restore dependencies
      shell: bash
      run: dotnet restore ./TicketBooking.csproj

    - name: Build
      shell: bash
      run: dotnet build ./TicketBooking.csproj --configuration Release --no-restore

    - name: Test
      shell: bash
      run: dotnet test ./TicketBooking.csproj --no-restore --verbosity normal
